### ISSUE TITLE
REG ERR

### ISSUE THREAD

**Issue by Andrzejone** [Shmalle/automatic-discord-message#1]
![image](https://user-images.githubusercontent.com/39127677/116951957-b4dfe080-ac89-11eb-86bb-786a0a57b0b9.png)
everytime the same. I tried diff servers and channels.The same wit powershell. Don't understand
Installed python 3.8, added path

**Comment by Shmalle** [comment]
I see. Sorry for the late reply, I think I have provided parts in the code that were for more specific use. However, I guess there must be something wrong with the variables, as the screenshot PARTLY shows me. However, I suggest checking if you have implemented **every** ID (Server-ID, Channel-ID). Check and tell me if you did so.

**Comment by Andrzejone** [comment]
You were right. Working well.
Can this run on linux tho?

**Comment by Shmalle** [comment]
Umm basically its just python so yea it is supposed to work on Linux as well if you set the paths to those textfiles correctly.

**Comment by Shmalle** [comment]
Ima close this since I havent received any reply.
